#
# MPI multiprecision maths library (from gpg)
#

obj-$(CONFIG_CRYPTO_MPILIB) = \
	generic_mpih-lshift.o		\
	generic_mpih-mul1.o		\
	generic_mpih-mul2.o		\
	generic_mpih-mul3.o		\
	generic_mpih-rshift.o		\
	generic_mpih-sub1.o		\
	generic_mpih-add1.o		\
	mpicoder.o			\
	mpi-bit.o			\
	mpih-cmp.o			\
	mpih-div.o			\
	mpih-mul.o			\
	mpi-pow.o			\
	mpiutil.o

